server:
  port: 8088

spring:
  datasource:
    username: root
    password: ilovehaohao_2020..,M
    url: jdbc:mysql://118.24.218.169:3306/test?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  type-aliases-package: com.meng.entity