spring:
  datasource:
    master:
      jdbc-url: jdbc:mysql://192.168.200.199:3306/read_write_splitting?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&useSSL=false&serverTimezone=Asia/Shanghai
      username: root
      password: 362623
      driver-class-name: com.mysql.cj.jdbc.Driver
    slave1:
      jdbc-url: jdbc:mysql://192.168.200.200:3306/read_write_splitting?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&useSSL=false&serverTimezone=Asia/Shanghai
      username: huaxin   # 只读账户
      password: 362623
      driver-class-name: com.mysql.cj.jdbc.Driver
    slave2:
      jdbc-url: jdbc:mysql://192.168.200.201:3306/read_write_splitting?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&useSSL=false&serverTimezone=Asia/Shanghai
      username: huaxin   # 只读账户
      password: 362623
      driver-class-name: com.mysql.cj.jdbc.Driver

#MyBatis
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: huaxin.entity

